services:
  backend:
    build: .
    container_name: clipq-backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env # Load environment variables including GOOGLE_API_KEY
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: .
    container_name: clipq-frontend
    command: streamlit run frontend/ui.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - CLIPQ_API_URL=http://backend:8000
    depends_on:
      - backend
